#!/bin/bash
TRUE="true"
FALSE="false"
SCRIPT_NAME=$0
SCRIPT_DIR=$(dirname $(readlink -e $SCRIPT_NAME))

. ${SCRIPT_DIR}/tools.sh

#echo "DOCKER_BRIDGE_IP=$DOCKER_BRIDGE_IP"

#service sshd start
#/etc/init.d/ssh start
#nohup /usr/sbin/sshd -D > /var/log/sshd.log 2>&1

SRV_HDFS_NAMENODE="hdfs_nn"
HADOOP_CONF_CORE=$HADOOP_CONF_DIR/core-site.xml
HADOOP_CONF_HDFS=$HADOOP_CONF_DIR/hdfs-site.xml
HADOOP_TMP_DIR=/opt/hdfs_data
HDFS_NAMENODE_VOLUME=$HADOOP_TMP_DIR/dfs/name

HDFS=${HADOOP_HOME}/bin/hdfs
ACTION_NAMENODE="namenode"
ACTION_SECONDARY_NAMENODE="secondarynamenode"
ACTION_DATANODE="datanode"
OPTION_DEBUG="--debug"
#ACTION_STOP="stop"
OPTION_CONFIG="--config"
NAMENODE_OPTION_FORMAT="--format"

SRV_RESOLVER=/opt/srv_resolver.sh

APP_HOME=$SCRIPT_DIR
PID_DIR=$APP_HOME/logs/pid
PID_FILE=hdfs.pid

unset action
debug=$FALSE
unset conf_dir
unset namenode_format
#LOGS_DIR
#LOG_FILE

function func_usage(){
    #echo "${BASH_ARGV[${#BASH_ARGV[@]}-1]} [OPTION] <ACTION>"
    echo "$SCRIPT_NAME [OPTION] <ACTION>"
    echo ""
    echo "ACTION"
    echo ""
    echo " $ACTION_NAMENODE [$NAMENODE_OPTION_FORMAT]"
    echo " $ACTION_SECONDARY_NAMENODE"
    echo " $ACTION_DATANODE"
    echo ""
    echo "OPTION"
    echo " $OPTION_DEBUG"
    echo " $OPTION_CONFIG confdir"
#    echo " $ACTION_STOP"
#    exit
}

function func_check_hdfs_formatted(){
    if [ -d $HDFS_NAMENODE_VOLUME ]; then
        echo $TRUE
    else
        echo $FALSE
    fi
}

#function func_configure_hdfs(){
#    local unset hdfs_nn_ip
#    while true; do
#        hdfs_nn_ip=$($SRV_RESOLVER -i $SRV_HDFS_NAMENODE | awk '{print $1}')
#        if [ ! -z $hdfs_nn_ip ]; then
#            echo "$SRV_HDFS_NAMENODE is resolved as $hdfs_nn_ip"
#            if [ ! -z $hdfs_nn_ip ]; then
#                sed -i 's/HDFS_NAMENODE/'"$hdfs_nn_ip"'/g' $HADOOP_CONF_CORE
#            fi
#            break
#        else
#            echo "CANNOT resolve service, $SRV_HDFS_NAMENODE"
#            sleep 1
#        fi
#
#    done
#}

function func_configure(){
#    echo "HADOOP_CONF_CORE=$HADOOP_CONF_CORE"
#    echo "HADOOP_CONF_HDFS=$HADOOP_CONF_HDFS"
    tool_template_fill_in_in_place $HADOOP_CONF_CORE "NAMENODE_SERVICE_NAME" $NAMENODE_SERVICE_NAME
    tool_template_fill_in_in_place $HADOOP_CONF_HDFS "SECONDARY_NAMENODE_SERVICE_NAME" $SECONDARY_NAMENODE_SERVICE_NAME
}

function func_parse_args(){
   local argp=0
   local argv=("$@")
   local argn=${#argv[@]}
   local unset remained_args
   ((remained_args=argn-argp))

   while true; do
       ((remained_args=argn-argp))
       if [[ ${argv[argp]} == $ACTION_NAMENODE ]]; then
           if [ $remained_args -eq 2 ] && [[ ${argv[argp+1]} == $NAMENODE_OPTION_FORMAT ]]; then
               namenode_format=true
           elif [ ! $remained_args -eq 1 ]; then
               func_usage
           fi
           action=$ACTION_NAMENODE
           ((argp++))
           break
       elif [ $remained_args -eq 1 ] && [[ ${argv[argp]} == $ACTION_SECONDARY_NAMENODE ]]; then
           action=$ACTION_SECONDARY_NAMENODE
           ((argp++))
           break
       elif [ $remained_args -eq 1 ] && [[ ${argv[argp]} == $ACTION_DATANODE ]]; then
           action=$ACTION_DATANODE
           ((argp++))
           break
       elif [[ ${argv[argp]} == $OPTION_DEBUG ]]; then
           debug=$TRUE
           ((argp++))
           continue
       elif [[ ${argv[argp]} == $OPTION_CONFIG ]]; then
           conf_dir=${argv[argp+1]}
           ((argp=argp+2))
           continue
       else
           func_usage
       fi
       break
   done

   echo $action
}

#function func_check_process(){}

function func_init_log(){
    if [ ! -d $PID_DIR ]; then
         mkdir -p $PID_DIR
    fi

    if [ -f $PID_DIR/$PID_FILE ]; then
         rm $PID_DIR/$PID_FILE
    fi
}

function func_debug(){
    while true; do
        echo "debug it!"
        sleep 1
    done
}

function action_run_namenode(){
#    sed -i 's/HDFS_NAMENODE/localhost/g' $HADOOP_CONF_CORE
    local cmd=""
    local is_formatted=$(func_check_hdfs_formatted)
    if [ $namenode_format ] && [[ $is_formatted == $FALSE ]]; then
        cmd="$HDFS namenode -format && "
    fi

    if [ -z $conf_dir ]; then
        cmd="$cmd $HDFS namenode"
    else
        cmd="$cmd $HDFS $OPTION_CONFIG $conf_dir namenode"
    fi

    if [[ $debug == $TRUE ]]; then
        echo "here!!"
        eval $cmd &
        func_debug
    else
        echo "there!!"
        eval $cmd
    fi
}

function action_run_secondary_namenode(){
    local unset cmd

    if [ -z $conf_dir ]; then
        cmd="$HDFS secondarynamenode"
#        eval $HDFS secondarynamenode
    else
        cmd="$HDFS $OPTION_CONFIG $conf_dir secondarynamenode"
#       eval $HDFS $OPTION_CONFIG $conf_dir secondarynamenode
    fi

    if [[ $debug == $TRUE ]]; then
        eval $cmd &
        func_debug
    else
        eval $cmd
    fi
}

function action_run_datanode(){
#    func_configure_hdfs
    local unset cmd

    if [ -z $conf_dir ]; then
        cmd="$HDFS datanode"
#        eval $HDFS datanode
    else
        cmd="$HDFS $OPTION_CONFIG $conf_dir datanode"
#        eval $HDFS $OPTION_CONFIG $conf_dir datanode
    fi

    if [[ $debug == $TRUE ]]; then
        eval $cmd &
        func_debug
    else
        eval $cmd
    fi
}


function func_run_action(){
    case "$action" in
        namenode)
            func_configure
            action_run_namenode
            ;;
        secondarynamenode)
            func_configure
            action_run_secondary_namenode
            ;;
        datanode)
            func_configure
            action_run_datanode
            ;;
        *)
            func_usage
            ;;
    esac
}

argv=($@)
echo $@
func_parse_args ${argv[@]}
#func_check_process
func_init_log
func_run_action
